const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path');const {createServer}=require('../server.cjs');
(async()=>{const server=createServer({key:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{});let count=0;const check=(name,v)=>{assert.ok(v,name);count++;};try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
await page.evaluate(()=>{const year=new Date().getFullYear();state.games=['regular','interleague','cs','japan_series'].map((competition,i)=>normalizeGame({id:'phase'+i,date:year+'-04-0'+(i+1),competition,myTeam:'baystars',opponent:i===1?'ロッテ':'阪神',venue:'横浜スタジアム',result:['win','lose','win','draw'][i]}));saveState();renderDashboard();});
check('home season excludes CS and Japan Series',(await page.locator('.metric').first().textContent()).includes('2試合'));
check('home has independent cards',await page.locator('.competition-cards .metric').count()===3);
await page.click('[data-competition-view="cs"]');check('CS shortcut selects CS',await page.inputValue('#analysis-competition')==='cs');check('CS has only its result',(await page.locator('.analysis-metrics .metric').first().textContent()).includes('1勝 0敗 0分'));check('season comparison hidden for CS',!(await page.isVisible('#season-comparison')));check('separate CS and Japan rows',await page.locator('#competition-table tbody tr').count()===4);
await page.selectOption('#analysis-competition','japan_series');check('Japan Series separate',(await page.locator('.analysis-metrics .metric').first().textContent()).includes('0勝 0敗 1分'));
await page.click('#analysis-share');check('share inherits competition',await page.inputValue('#share-competition')==='japan_series');check('share text labels competition',(await page.inputValue('#share-caption')).includes('日本シリーズ'));await page.click('#share-close');
await page.selectOption('#analysis-competition','season');check('season comparison only uses season',await page.isVisible('#season-comparison'));
await page.click('#nav-list');await page.selectOption('#list-competition','cs');check('list CS only',await page.locator('.game-card').count()===1);check('card labels CS',(await page.textContent('.gc-meta')).includes('CS'));await page.click('[data-edit="phase2"]');check('edit retains CS',await page.inputValue('#f-competition')==='cs');await page.selectOption('#f-competition','japan_series');await page.click('#f-save');await page.waitForSelector('#scr-list:not([hidden])');check('edited category saved',await page.evaluate(()=>state.games.find(g=>g.id==='phase2').competition==='japan_series'));check('saved game not hidden by old filter',await page.locator('[data-edit="phase2"]').count()===1);
await page.click('#add-game');await page.selectOption('#f-competition','cs');await page.selectOption('#f-opponent-select',{label:'巨人'});await page.selectOption('#f-result','win');await page.click('#f-save');await page.waitForSelector('#scr-list:not([hidden])');check('new CS record saved',await page.evaluate(()=>state.games.at(-1).competition==='cs'));
await page.reload();check('classification persists',await page.evaluate(()=>state.games.find(g=>g.id==='phase2').competition==='japan_series'));
await page.click('#home-memo');await page.fill('#memo-json',JSON.stringify({games:[{date:'2024-10-26',myTeam:'baystars',competition:'japan_series',opponent:'ソフトバンク',result:'win'}]}));await page.click('#memo-preview');check('memo preview labels Japan Series',(await page.textContent('#memo-review')).includes('日本シリーズ'));await page.click('#memo-import');check('memo imports category',await page.evaluate(()=>state.games.at(-1).competition==='japan_series'));
const out=process.env.BAYDIARY_QA_DIR;
for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});await page.click('#nav-dashboard');check('home no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(out&&width===390)await page.screenshot({path:path.join(out,'competition-home.png'),fullPage:true});await page.click('#nav-analysis');await page.selectOption('#analysis-competition','japan_series');check('analysis no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(out&&width===390)await page.screenshot({path:path.join(out,'competition-analysis.png'),fullPage:true});}
check('no runtime errors',errors.length===0);console.log(JSON.stringify({passed:count,errors}));}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1);});
