const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');const {createServer}=require('../server.cjs');
(async()=>{
 const sample={date:'2025-04-12',myTeam:'baystars',opponent:'阪神',venue:'横浜スタジアム',score:{bay:5,opp:3},result:'win',sourceText:'4/12 阪神戦 5-3勝ち 友人と',highlight:'逆転勝ち',companions:['友人']};
 const server=createServer({key:'test-only',fetchImpl:async()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({games:[sample]})}]}]})})});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{});let checks=0;const check=(name,v)=>{assert.ok(v,name);checks++;};
 try{
 const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 await page.click('#home-share');check('empty record cannot generate file',await page.isDisabled('#share-download'));await page.click('#share-close');
 await page.evaluate(()=>{state.games=[normalizeGame({id:'existing',myTeam:'baystars',date:'2025-04-12',opponent:'阪神',venue:'横浜スタジアム',result:'win',companions:['SECRET NAME'],highlight:'PRIVATE NOTE',photoIds:['photo-unchanged']})];state.settings.actualRecords={baystars:{2025:{win:60,lose:40,draw:0}}};saveState();renderDashboard();});
 await page.click('#home-share');await page.selectOption('#share-year','2025');await page.waitForFunction(()=>!document.getElementById('share-download').disabled);
 check('caption has branding',(await page.inputValue('#share-caption')).includes('#ベイ日記'));check('caption excludes private fields',!(await page.inputValue('#share-caption')).includes('PRIVATE')&&!(await page.inputValue('#share-caption')).includes('SECRET'));
 check('share file prepared before user gesture',await page.evaluate(()=>shareFile.type==='image/png'&&shareFile.size>10000));
 const downloadPromise=page.waitForEvent('download');await page.click('#share-download');const image=await downloadPromise;const imageBytes=fs.readFileSync(await image.path());check('download PNG signature',imageBytes.subarray(1,4).toString()==='PNG');
 const output=process.env.BAYDIARY_QA_DIR;if(output){fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'share-card.png'),imageBytes);await page.screenshot({path:path.join(output,'share-mobile.png'),fullPage:true});}
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.shared={name:data.files[0].name,text:data.text};}});});await page.click('#share-native');check('native share receives PNG and caption',await page.evaluate(()=>shared.name.endsWith('.png')&&shared.text.includes('100.0%')));
 await page.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{throw new DOMException('Cancel','AbortError');}}));await page.click('#share-native');check('cancel is not an error',(await page.textContent('#share-status')).includes('キャンセル'));
 await page.selectOption('#share-mode','venue');check('venue picker appears',await page.isVisible('#share-venue'));await page.selectOption('#share-team','tigers');check('different team cannot share stale image',await page.isDisabled('#share-native'));await page.click('#share-close');
 await page.click('#home-memo');check('memo screen',await page.isVisible('#scr-memo'));await page.setInputFiles('#memo-files',[{name:'日記.txt',mimeType:'text/plain',buffer:Buffer.from('4/12 阪神戦 5-3勝ち 友人と')},{name:'別の日.md',mimeType:'text/markdown',buffer:Buffer.from('5/1 巨人戦')}]);check('multiple files loaded',(await page.inputValue('#memo-text')).includes('別の日.md'));await page.fill('#memo-year','2025');await page.click('#memo-analyze');await page.waitForFunction(()=>document.getElementById('memo-status').textContent.includes('完了'));
 check('AI response becomes editable JSON',JSON.parse(await page.inputValue('#memo-json')).games.length===1);check('existing duplicate starts unchecked',await page.locator('[data-memo-row]:checked').count()===0);check('AI does not autosave',await page.evaluate(()=>state.games.length===1));
 const draft={games:[sample,{...sample,date:'2025-05-01',opponent:'巨人',sourceText:'<img src=x onerror="window.injected=1">'},{...sample,date:null}]};await page.fill('#memo-json',JSON.stringify(draft));await page.click('#memo-preview');check('valid new row selected only',await page.locator('[data-memo-row]:checked').count()===1);check('missing date is blocked',await page.locator('[data-memo-row="2"]').isDisabled());check('source escaped',await page.locator('#memo-review img').count()===0);
 await page.evaluate(()=>{window.oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('quota','QuotaExceededError');};});await page.click('#memo-import');check('storage failure retains state',await page.evaluate(()=>state.games.length===1));check('storage error displayed',(await page.textContent('#memo-review-status')).includes('保存容量'));await page.evaluate(()=>Storage.prototype.setItem=window.oldSet);
 await page.click('#memo-import');check('appends without erasing',await page.evaluate(()=>state.games.length===2&&state.games[0].photoIds[0]==='photo-unchanged'&&state.settings.actualRecords.baystars[2025].win===60));check('original memo retained',await page.evaluate(()=>state.games[1].sourceMemo.includes('<img')));check('double click cannot duplicate',await page.isDisabled('#memo-import'));
 await page.click('#memo-preview');check('reimport excludes known records',await page.locator('[data-memo-row]:checked').count()===0);
 await page.fill('#memo-json',JSON.stringify({games:[{...sample,date:'2025-06-01'}]}));await page.click('#memo-preview');await page.fill('#memo-json','{"games":[]}');check('editing invalidates reviewed selection',await page.isDisabled('#memo-import'));
 await page.setInputFiles('#memo-json-file',{name:'draft.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({games:[{...sample,date:'2025-06-01'}]}))});await page.waitForFunction(()=>!document.getElementById('memo-import').disabled);check('JSON file load previews rows',await page.locator('[data-memo-row]').count()===1);
 const jsonPromise=page.waitForEvent('download');await page.click('#memo-download');const jsonDownload=await jsonPromise;check('JSON export valid',JSON.parse(fs.readFileSync(await jsonDownload.path(),'utf8')).games.length===1);
 await page.route('**/api/memo-extract',route=>route.fulfill({status:503,json:{error:'AI接続設定がまだありません'}}));await page.click('#memo-analyze');await page.waitForFunction(()=>document.getElementById('memo-status').textContent.includes('接続設定'));check('failure keeps memo and draft',(await page.inputValue('#memo-text')).includes('4/12')&&JSON.parse(await page.inputValue('#memo-json')).games.length===1);
 if(output)await page.screenshot({path:path.join(output,'memo-mobile.png'),fullPage:true});
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});check('memo no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('#nav-dashboard');await page.click('#home-share');check('share dialog no overflow '+width,await page.evaluate(()=>document.getElementById('share-dialog').scrollWidth<=document.getElementById('share-dialog').clientWidth+1));await page.click('#share-close');await page.click('#home-memo');}
 await page.reload();check('saved records persist',await page.evaluate(()=>state.games.length===2&&state.games[1].sourceMemo.includes('<img')));check('no JS errors',errors.length===0);
 console.log(JSON.stringify({passed:checks,errors,output:output||null}));
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1);});
